# -*- coding: utf-8 -*-
"""Two Player Tic Tac Toe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BDD6bMuyqqvUflY4W7MHzU9yhPB40JVs
"""

# A TWO PLAYER TIC-TAC-TOE GAME:


# Some necessary functions:
def count_space(matrix):
  '''
This Function returns the number of empty spaces.
 
  '''
  count = 0
  for i in range(3):
    for j in range(3):
      if matrix[i][j] == "|   |":
        count = count + 1
  return(count)


def win(matrix):
  '''
1. returns "x_win" or "o_win" on the basis of who won
2. returns None if the game is still not over
3. returns "draw" if the game is tied

  '''
  for i in range(3):
    if (matrix[i][0] == "| 1 |") and (matrix[i][1] == "| 1 |") and (matrix[i][2] == "| 1 |"):
      return("x_win")
    elif (matrix[i][0] == "| 0 |") and (matrix[i][1] == "| 0 |") and (matrix[i][2] == "| 0 |"):
      return("o_win")
    
  
  for j in range(3):
    if (matrix[0][j] == "| 1 |") and (matrix[1][j] == "| 1 |") and (matrix[2][j] == "| 1 |"):
      return("x_win")
    elif (matrix[0][j] == "| 0 |") and (matrix[1][j] == "| 0 |") and (matrix[2][j] == "| 0 |"):
      return("o_win")
    
  
  if (matrix[0][0] == "| 1 |") and (matrix[1][1] == "| 1 |") and (matrix[2][2] == "| 1 |"):
    return("x_win")
  elif (matrix[0][0] == "| 0 |") and (matrix[1][1] == -1) and (matrix[2][2] == -1):
    return("o_win")
  elif (matrix[0][2] == "| 1 |") and (matrix[1][1] == "| 1 |") and (matrix[2][0] == "| 1 |"):
    return("x_win")
  elif (matrix[0][2] == "| 0 |") and (matrix[1][1] == "| 0 |") and (matrix[2][0] == "| 0 |"):
    return("o_win")
  elif count_space(matrix) == 0:
    return("draw")

  else:
    return(None)

def space(matrix):
  '''
  This function returns the list of empty spaces on the board
  '''
  list0 = []
  for i in range(3):
    for j in range(3):
      if matrix[i][j] == "|   |":
        list0.append([i,j])
  return(list0)

# Initial inputs from the user

count = 0
board = [["|   |" for x in range(3)] for y in range(3)]
player_1 = str(input("Enter the name of Player 1: "))
player_2 = str(input("Enter the name of Player 2: "))

# Game Loop begins from here: 

while(True):

  print("Board Status: ")
  for i in board:
    print("----- ----- -----")
    print(" ".join(i))  
    print("----- ----- -----")

  if count%2 == 0:
    a,b = map(int, input(f"{player_1}, please choose where you want to place your '1': ").split())
    if [a,b] not in space(board):
      print("The space is already occupied")
      continue
    else:
      board[a][b] = "| 1 |"
      if win(board) == "x_win":
        print(f"Congratulations {player_1}, you won !!!")
        for i in board:
            print("----- ----- -----")
            print(" ".join(i))  
            print("----- ----- -----")
        break
      elif win(board) == "draw":
        print(f"The Game ends in a Draw")
        for i in board:
            print("----- ----- -----")
            print(" ".join(i))  
            print("----- ----- -----")
        break
      elif win(board) == None:
        count = count + 1
        continue
   
  if count%2 != 0:
    a,b = map(int, input(f"{player_2}, please choose where you want to place your '0': ").split())
    if [a,b] not in space(board):
      print("The space is already occupied")
      continue
    else:
      board[a][b] = "| 0 |"
      if win(board) == "o_win":
        for i in board:
            print("----- ----- -----")
            print(" ".join(i))  
            print("----- ----- -----")
        print(f"Congratulations {player_2}, you won !!!")
        break
      elif win(board) == "draw":
        print(f"The Game ends in a Draw")
        for i in board:
            print("----- ----- -----")
            print(" ".join(i))  
            print("----- ----- -----")
        break
      elif win(board) == None:
        count = count + 1
        continue

